model_params:
  model_name: 'NBeats'
  stacks: [30]
  layers: [4]
  layer_size: [512]

exp_params:
#  variate: ['uni', 'multi'] #['single', 'multiple']

  sliding_window: [ 120 ]
  selection_metric: 'RMSE' # one of ['RMSE', 'MAE', 'MAPE']

  train_valid_ratio: 0.9

  external_flag: [True, False] #[True, False]
  external_features: ['month_day', 'weekday', 'holiday', 'DHI', 'DNI', 'GHI', 'Dew Point', 'Solar Zenith Angle', 'Wind Speed', 'Relative Humidity', 'Temperature']

  test_flag: False
  last_version: 11

  # DNNs
  batch_size: [128] #[50, 100, 150]
  learning_rate: [0.001] #[0.1, 0.01, 0.001]
  num_workers: 0
  normalization: ['minmax'] #['none', 'minmax', 'standard']

  prediction_interval: 0.95

  data_folder: '../../../../PSML/processed_datasets/forecasting'

trainer_params:
  max_epochs: 2 # by default it's 50
  gpus: [3]

logging_params:
  save_dir: './../logs'
  name: 'NBeats'
  manual_seed: 0