model_params:
  model_name: 'svr'
  kernel: ['rbf'] #, 'poly', 'rbf', 'sigmoid']


exp_params:
  variate: [ 'uni', 'multi' ] #['uni', 'multi']
  sliding_window: [ 120 ]
  selection_metric: 'RMSE' # one of ['RMSE', 'MAE', 'MAPE']

  external_feature_flag: [True, False]
  external_features: ['month_day', 'weekday', 'holiday', 'DHI', 'DNI', 'GHI', 'Dew Point', 'Solar Zenith Angle', 'Wind Speed', 'Relative Humidity', 'Temperature']

  train_valid_ratio: 2000

  test_flag: False
  last_version: 17

  prediction_interval: 0.95

  data_folder: '../../../../PSML/processed_datasets/forecasting'

trainer_params:

logging_params:
  save_dir: './../logs'
  name: 'svr'
  manual_seed: 0