model_params:
  model_name: 'cnn'
  dropout: [0.1] #[0., 0.1]
  hidden_layers: [[32, 64]] #[[32, 64, 128]]
  kernel_size: [[4, 4]] #[[8, 8, 8]]
  stride: [[2, 2]] # [[2, 2, 4]]
  pooling: ['max'] #['max', 'avg', 'AdaptiveAvg', 'AdaptiveMax', 'lp']

exp_params:
  train_valid_ratio: 0.8
  label_constraints: [True] #[True, False]

  test_flag: False
  last_version: 23

  # DNNs
  batch_size: [50] #[50, 100, 150]
  learning_rate: [0.01] #[0.1, 0.01, 0.001]
  num_workers: 0

  normalization: ['standard'] #['none', 'minmax', 'standard']

  target_name: ['fault', 'location', 'starttime']

  data_path: '../../../../PSML/processed_datasets/classification.pkl'

trainer_params:
  max_epochs: 2 # NOTE: default is 50
  gpus: [1]

logging_params:
  save_dir: './../logs'
  name: 'cnn'
  manual_seed: 0