model_params:
  model_name: 'TapNet'

  dropout: [0.]

  use_cnn: [True]
  filters: [[256, 256, 128]]
  kernels: [[8, 5, 3]]
  dilation: [1]
  layers: [[500, 300]]

  use_lstm: [True]
  lstm_dim: [128]

  use_rp: [True]
  rp_params: [[-1, 3]]
  use_metric: [False]
  metric_param: [0.01]

exp_params:
  train_valid_ratio: 0.8
  label_constraints: [True] #[ True, False ]

  test_flag: False
  last_version: 15

  # DNNs
  batch_size: [ 50 ] #[50, 100, 150]
  learning_rate: [0.00001] #1e-5
  num_workers: 0
  normalization: ['standard'] #['none', 'minmax', 'standard']

  target_name: ['fault', 'location', 'starttime']

  weight_decay: [0.001]

  data_path: '../../../../PSML/processed_datasets/classification.pkl'

trainer_params:
  max_epochs: 2 # NOTE: by default it is 50
  gpus: [3]

logging_params:
  save_dir: './../logs'
  name: 'TapNet'
  manual_seed: 0